# Generated by Django 5.0.6 on 2024-06-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField()),
                ("create_at", models.DateTimeField(auto_now=True)),
                ("accuracy", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_deleted", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoryAdmin",
            fields=[
                (
                    "history_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.history",
                    ),
                ),
            ],
            bases=("app.history",),
        ),
    ]
